version: "3"

networks:
  datapatch:

services:
  mysql56:
    build: docker/images/mysql56
    container_name: datapatch-mysql56
    ports:
      - 13356:3306
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL56_PASSWORD
    networks:
      - datapatch

  mysql57:
    build: docker/images/mysql57
    container_name: datapatch-mysql57
    ports:
      - 13357:3306
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL57_PASSWORD
    networks:
      - datapatch

  production:
    build: docker/images/mysql-production
    container_name: datapatch-mysql-production
    ports:
      - 13500:3306
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_PRODUCTION_PASSWORD
    networks:
      - datapatch
